name: Latest commit message made by user
on:
  push:
    branches:
      - main

jobs:
  update-readme-with-last-commit:
    name: Update this repo's README with latest commit made
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: estarossa0/readme-last-commit@master
